---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Creating ganesha-ha.conf file
    template: src=ganesha-ha.conf
              dest="{{ ha_base_dir }}"

# We don't need quotes in the template file ganesha-ha.conf
# The below block can be commented out.

  # - name: Replacing quotes in conf file
  #   replace: dest="{{ ha_base_dir }}"/ganesha-ha.conf
  #            regexp='"(((VIP.*)\n*)*)"$'
  #            replace='\1'

